# =========================
# BASES
# =========================

proteinasKG = [
    "Peito de frango", "Coxa de frango", "Sobrecoxa de frango", "Frango inteiro",
    "Filé de frango", "Asa de frango", "Frango desfiado",

    "Patinho", "Acém", "Alcatra", "Músculo bovino", "Coxão mole",
    "Coxão duro", "Lagarto", "Fraldinha", "Picanha", "Contrafilé",
    "Maminha", "Filé mignon", "Costela bovina", "Cupim", "Acém moído",
    "Carne moída", "Carne de segunda",

    "Lombo suíno", "Pernil suíno", "Costelinha suína", "Bisteca suína",
    "Panceta", "Barriga suína", "Filé suíno",

    "Salmão", "Tilápia", "Bacalhau", "Merluza", "Sardinha",
    "Atum", "Truta", "Pescada", "Dourado", "Corvina",
    "Cação", "Anchova", "Linguado",

    "Frango caipira", "Fígado bovino", "Fígado de frango",
    "Moela de frango", "Coração de frango",

    "Carne suína moída", "Carne bovina moída magra",
    "Costela bovina", "Peixe branco",

    "Cordeiro", "Peru", "Peito de peru",
    "Linguiça toscana", "Linguiça calabresa",
    "Linguiça de frango", "Linguiça bovina",

    "Filé de peixe branco", "Peixe pescada amarela",
    "Peixe robalo", "Peixe namorado"
]

proteinasUN = [
    "Ovo", "Ovo caipira", "Ovo vermelho", "Ovo de codorna",

    "Hambúrguer bovino", "Hambúrguer de frango", "Hambúrguer suíno",
    "Hambúrguer artesanal",

    "Salsicha", "Salsicha de frango", "Salsicha bovina",
    "Salsicha hot dog",

    "Nuggets de frango", "Empanado de frango",
    "Almôndega",

    "Tofu", "Tofu defumado", "Tempeh",

    "Queijo coalho", "Queijo muçarela",
    "Queijo prato",

    "Presunto", "Peito de peru",

    "Sardinha enlatada", "Atum enlatado",

    "Hambúrguer vegetal", "Proteína vegetal"
]

proteinasCF = [
    "Ovo", "Ovo caipira", "Ovo vermelho", "Ovo de codorna",
    "queijo mussarela", "queijo prato", "queijo minas",
    "queijo minas frescal", "queijo coalho", "queijo branco",
    "queijo cheddar", "queijo provolone", "queijo gouda", "queijo parmesão",
    "queijo fresco", "queijo meia cura", "queijo minas padrão", "queijo light",
    "requeijão", "requeijão light",
    "cottage", "ricota", "creme de ricota", "creme de queijo",
    "peito de peru", "presunto", "presunto magro", "blanquet de peru",
    "tofu",
    "pasta de amendoim", "pasta de amendoim integral",
    "pasta de castanha", "pasta de amêndoas", "pasta de castanha de caju",
    "coalhada", "coalhada seca",
   
    ]

carboidratosCF = [
    "pão francês", "pão francês integral",
    "pão de forma", "pão de forma integral",
    "pão integral", "pão caseiro",
    "pão de leite", "pão doce",
    "pão australiano", "pão multigrãos",
    "pão sírio", "pão árabe",
    "pão de queijo",
    "torrada", "torrada integral",
    "biscoito água e sal", "biscoito cream cracker",
    "biscoito integral", "biscoito doce",
    "bolacha maisena", "bolacha integral",
    "biscoito de polvilho", "sequilhos",
    "tapioca",
    "cuscuz",
    "aveia", "aveia em flocos", "aveia fina",
    "granola", "granola tradicional", "granola integral",
    "cereal matinal", "cereal integral",
    "sucrilhos", "flocos de milho",
    "milho",
    "bolo simples", "bolo de fubá", "bolo de cenoura",
    "bolo de chocolate", "bolo integral",
    "bolo de banana", "bolo de milho", "bolo de laranja",
    "croissant", "brioche", "rosca doce",
    "wrap", "wrap integral", "panqueca de banana",
    "crepioca"
]

frutas = [
    "banana", "banana prata", "banana nanica",
    "maçã", "maçã verde",
    "pera",
    "mamão", "mamão papaya",
    "melancia",
    "melão",
    "laranja", "laranja pera",
    "mexerica", "tangerina",
    "abacaxi",
    "manga",
    "uva", "uva verde", "uva roxa",
    "morango",
    "kiwi",
    "goiaba",
    "acerola",
    "caju",
    "pêssego",
    "ameixa",
    "figo",
    "caqui",
    "maracujá",
    "jabuticaba",
    "pitanga",
    "carambola",
    "graviola",
    "cupuaçu",
    "açaí",
    "framboesa",
    "amora",
    "mirtilo"
]

liquidos = [
    "iogurte natural", "iogurte integral", "iogurte desnatado",
    "iogurte grego", "iogurte proteico", "iogurte zero lactose",
    "iogurte com frutas", "iogurte com aveia", "iogurte com granola proteica",
    "leite", "leite integral", "leite desnatado", "leite sem lactose",
    "leite fermentado", "bebida láctea", "bebida láctea fermentada",
    "leite com proteína",
    "leite vegetal", "leite de soja", "leite de amêndoas",
    "leite de aveia", "leite de coco",
    "bebida proteica", "bebida vegetal proteica", "bebida de proteína",
    "shake proteico", "smoothie proteico",
    "kefir", "kefir de leite",
]

cereais = [
    "aveia em flocos", "granola tradicional", "granola com frutas",
    "granola sem açúcar", "granola crocante", "muesli tradicional",
    "muesli com frutas secas", "flocos de milho", "flocos de trigo",
    "flocos de arroz", "flocos de quinoa", "cereal puffado de milho",
    "cereal puffado de arroz", "cereal puffado de quinoa",
    "farelo de aveia", "farelo de trigo", "farelo de centeio",
    "farelo de arroz", "farelo de milho", "farelo de quinoa",
    "farelo de amaranto", "cereal de trigo integral",
    "cereal de arroz integral", "cereal de milho integral",
    "cereal de quinoa", "cereal de amaranto", "cereal de painço",
    "cereal de trigo sarraceno", "cereal de espelta",
    "granola orgânica", "granola diet", "granola light",
    "muesli crocante", "muesli de frutas vermelhas",
    "muesli tropical", "cereal com frutas secas",
    "cereal com castanhas", "cereal com sementes",
    "cereal de chocolate", "cereal de banana", "cereal de morango",
    "cereal com mel", "cereal com mel e nozes",
    "cereal integral com gergelim", "cereal integral com chia",
    "cereal integral com linhaça", "cereal de arroz tostado",
    "cereal de milho tostado", "cereal de trigo tostado",
    "cereal com amêndoas", "cereal com nozes",
    "cereal com aveia e mel", "cereal com frutas vermelhas",
    "cereal puffado com chocolate", "cereal diet sem açúcar",
    "cereal light com frutas", "cereal integral com damasco",
    "cereal integral com uva-passa", "cereal granulado de cacau",
    "cereal de milho em flocos", "cereal de trigo em flocos",
    "flocos de painço", "flocos de amaranto", "flocos de centeio",
    "flocos de espelta", "flocos de trigo sarraceno",
    "cereal com pedaços de frutas", "cereal proteico com aveia",
    "cereal proteico com soja", "cereal proteico com quinoa",
    "cereal vegano", "cereal sem glúten", "cereal sem lactose",
    "cereal integral sem açúcar", "cereal de arroz integral com chia",
    "cereal com linhaça e girassol", "cereal com castanha do pará",
    "cereal com semente de abóbora", "cereal com semente de girassol",
    "cereal de aveia e cacau", "cereal de aveia e morango",
    "cereal com quinoa e mel", "cereal de milho e mel",
    "cereal de trigo e mel", "cereal light com mel",
    "cereal integral crocante", "cereal sabor baunilha",
    "cereal sabor canela", "cereal sabor coco", "cereal sabor frutas",
    "cereal integral puffado", "cereal infantil",
    "cereal kids integral", "cereal kids com frutas"
]

farinhas = [
    "farinha de trigo", "Fermento em pó", "farinha de trigo integral",
    "farinha de aveia", "farinha de arroz", "farinha de centeio",
    "farinha de milho", "fubá de milho", "fubá mimoso",
    "farinha de quinoa", "farinha de amaranto", "farinha de espelta",
    "farinha de trigo sarraceno", "farinha de painço",
    "farinha de cevada", "farinha de arroz integral",
    "farinha de milho integral", "farinha de soja",
    "farinha de grão-de-bico", "farinha de linhaça",
    "farinha de coco", "farinha de castanha de caju",
    "farinha de amêndoas", "farinha de castanha do pará",
    "farinha de nozes", "farinha de chia", "farinha de banana verde",
    "farinha de tapioca", "polvilho doce", "polvilho azedo",
    "amido de milho (maizena)", "farinha láctea",
    "farinha de rosca (para preparo ocasional)", "farinha enriquecida",
    "farinha para bolo", "mistura para panqueca",
    "mistura para waffle", "farinha para muffin",
    "farinha pré-misturada integral", "farinha sem glúten",
    "farinha proteica", "farinha enriquecida com ferro",
    "farinha integral orgânica", "farinha de cereais múltiplos",
    "farinha de arroz branco", "farinha de quinoa integral",
    "farinha de amaranto integral", "farinha de espelta integral",
    "farinha de trigo orgânica", "farinha de milho flocada",
    "farinha de centeio integral", "farinha de aveia orgânica",
    "farinha de milho para bolo", "farinha de milho para mingau",
    "farinha de milho para polenta", "farinha de arroz para mingau",
    "farinha de tapioca hidratada", "farinha de trigo para cuscuz",
    "farinha de rosca integral", "farinha multiuso",
    "farinha enriquecida com vitaminas", "farinha com fibras",
    "mistura para pão caseiro", "mistura para pão integral",
    "farinha de sorgo", "farinha de painço integral",
    "farinha de trigo germinado", "farinha germinada mista",
    "farinha de arroz glutinada", "farinha para panificação",
    "mistura para crepioca", "mistura para panqueca integral",
    "farinha de arroz para panificação", "farinha nutritiva",
    "farinha para cookies", "farinha de aveia saborizada",
    "farinha de milho pré-cozida", "farinha para tapioca",
    "farinha de legumes desidratados", "farinha de beterraba",
    "farinha de cenoura", "farinha de batata",
    "farinha de mandioca fina", "farinha de mandioca grossa",
    "farinha de cevada torrada", "farinha de milho doce",
    "farinha de trigo com fermento", "farinha pão francês",
    "farinha de quinoa saborizada", "farinha enriquecida p/ café da manhã",
    "farinha integral sabor canela", "mistura pronta para mingau",
    "mistura pronta para aveia saborizada", "Goma de tapioca", "tapioca hidratada"
]

folhas_saladas = [
"Alface",
"Alface americana",
"Alface crespa",
"Alface lisa",
"Alface roxa",
"Alface mimosa",
"Alface frisée",
"Alface baby leaf",
"Alface romana",
"Alface iceberg",
"Rúcula",
"Rúcula selvagem",
"Agrião",
"Agrião da terra",
"Espinafre",
"Espinafre baby",
"Couve",
"Couve manteiga",
"Couve baby",
"Repolho",
"Repolho roxo",
"Repolho verde",
"Acelga",
"Acelga chinesa",
"Endívia",
"Endívia roxa",
"Almeirão",
"Chicória",
"Radicchio",
"Mostarda",
"Folha de mostarda",
"Folha de beterraba",
"Folha de cenoura",
"Folha de nabo",
"Folha de rabanete",
"Folha de brócolis",
"Folha de couve-flor",
"Escarola",
"Escarola crespa",
"Treviso",
"Baby rúcula",
"Mix de folhas verdes",
"Mix primavera",
"Mix mediterrâneo",
"Microgreens",
"Broto de alfafa",
"Broto de feijão",
"Broto de lentilha",
"Broto de ervilha",
"Broto de girassol",
"Broto de rúcula",
"Broto de beterraba",
"Broto de mostarda",
"Broto de trigo",
"Broto de milho",
"Broto de cebola",
"Broto de coentro",
"Broto de manjericão",
"Folha de manjericão",
"Manjericão roxo",
"Folha de hortelã",
"Hortelã pimenta",
"Folha de coentro",
"Folha de salsa",
"Salsinha crespa",
"Salsinha lisa",
"Folha de dill",
"Folha de erva-doce",
"Folha de funcho",
"Folha de cebola",
"Cebolinha verde",
"Folha de alho-poró",
"Folha de alho",
"Folha de louro fresco",
"Folha de taioba",
"Folha de ora-pro-nóbis",
"Folha de bertalha",
"Folha de beldroega",
"Folha de serralha",
"Folha de dente-de-leão",
"Folha de mostarda japonesa",
"Mizuna",
"Tatsoi",
"Pak choi",
"Bok choy",
"Komatsuna",
"Shiso",
"Perilla",
"Folha de uva",
"Folha de hibisco",
"Folha de amaranto",
"Folha de quinoa",
"Folha de espinafre selvagem",
"Folha de chicória roxa",
"Folha de rúcula baby roxa",
"Folha de alface baby mix"
]

carboidratos = [
    "Quinoa", "Cuscuz", "Aveia", "Milho verde", "Milho",
    "Polenta", "Fubá", "Farofa",

    "Grão-de-bico", "Lentilha", "Feijão carioca",
    "Feijão preto", "Feijão branco", "Ervilha",

    "Batata baroa", "Mandioquinha", "Inhame",
    "Cará", "Tapioca", "Cuscuz nordestino", "Cuscuz",
    "Arroz branco",
"Arroz integral",
"Arroz parboilizado",
"Arroz basmati",
"Arroz jasmim",
"Arroz arbóreo",
"Arroz selvagem",
"Arroz cateto",
"Arroz vermelho",
"Arroz negro",

"Feijão carioca",
"Feijão preto",
"Feijão branco",
"Feijão fradinho",
"Feijão rosinha",
"Feijão jalo",
"Feijão manteiguinha",
"Feijão azuki",
"Feijão rajado",
"Feijão vermelho",

"Lentilha",
"Grão-de-bico",
"Ervilha seca",
"Ervilha verde",
"Fava",
"Soja em grão",
"Soja preta",
"Soja amarela",

"Milho verde",
"Milho seco",
"Milho para canjica",
"Canjica branca",
"Canjica amarela",

"Quinoa branca",
"Quinoa vermelha",
"Quinoa preta",

"Amaranto",
"Trigo em grão",
"Trigo para quibe",
"Trigo integral",
"Cevada",
"Centeio",
"Sorgo",
"Painço",
"Teff",
"Batata inglesa",
"Batata asterix",
"Batata bolinha",
"Batata doce branca",
"Batata doce roxa",
"Batata doce laranja",
"Batata yacon",
"Mandioca",
"Aipim",
"Macaxeira",
"Mandioca amarela",
"Mandioca branca",
"Inhame",
"Cará",
"Cará roxo",
"Cará branco",
"Mandioquinha",
"Batata baroa",
"Nabo",
"Rabanete",
"Beterraba",
"Cenoura",
"Abóbora japonesa",
"Abóbora moranga",
"Abóbora cabotiá",
"Abóbora paulista",
"Chuchu",
"Abobrinha",
"Fubá",
"Fubá mimoso",
"Fubá grosso",
"Polenta",
"Cuscuz de milho",
"Cuscuz de arroz",
"Arroz integral vermelho",
"Arroz integral negro",
"Milheto",
"Grão de cevada perlada",
"Batata doce japonesa",
"Batata doce biofortificada",
"Inhame chinês",
"Inhame africano",
"Cará-do-ar",
"Cará-de-espinho",
"Creme de arroz",
"Creme de milho",
"Semolina",
"Sêmola de trigo",
"Trigo sarraceno",
"Trigo para canjica",
"Grão de bico torrado",
"Lentilha vermelha",
"Lentilha verde",
"Lentilha marrom",
"Feijão mungo",
"Feijão branco gigante",
"Feijão manteiga",
"Milho roxo",
"Milho crioulo",
"Arroz cateto integral",
"Arroz agulhinha",
"Goma de tapioca fresca",
"Cuscuz marroquino",
"Cuscuz integral",
"Milho canjicado",
"Milho flocão",
"Sorgo em grão",
"Sorgo moído",
"Teff branco",
"Teff escuro"
]

massas = [
    "Macarrão Espaguete", "Macarrão Penne", "Macarrão Fusilli", "Macarrão Rigatoni", "Macarrão Linguine",
    "Macarrão Talharim", "Macarrão Tagliatelle", "Macarrão Farfalle", "Macarrão Parafuso",
    "Nhoque", "Ravioli", "Capeletti", "Tortellini",
    "Canelone",

    "Macarrão integral", "Macarrão de arroz",
    "Macarrão de grão duro",
    
]

molhos = [
    "Molho de tomate", "Molho de tomate rústico",
    "Molho de tomate caseiro", "Molho de tomate com manjericão",

    "Molho branco", "Molho branco cremoso",
    "Molho quatro queijos", "Molho cheddar",

    "Molho pesto", "Molho de ervas",
    "Molho de manjericão", "Molho de salsinha",

    "Molho de alho e azeite", "Molho de alho cremoso",
    "Molho de mostarda", "Molho de mostarda e mel",

    "Molho barbecue", "Molho agridoce",
    "Molho picante", "Molho chipotle",

    "Molho de cogumelos", "Molho funghi",
    "Molho madeira", "Molho bolonhesa",

    "Molho rosé","Molho de iogurte", "Molho de limão",

    "Molho de queijo", "Molho parmesão"
]

caldos = [
    {"nome": "Caldo de legumes", "forma": "liquido"},
    {"nome": "Caldo de frango", "forma": "liquido"},
    {"nome": "Caldo de carne", "forma": "liquido"},

    {"nome": "Tablete de caldo de legumes", "forma": "tablete"},
    {"nome": "Tablete de caldo de frango", "forma": "tablete"},
    {"nome": "Tablete de caldo de carne", "forma": "tablete"},

    {"nome": "Caldo em pó de legumes", "forma": "po"},
    {"nome": "Caldo em pó de frango", "forma": "po"},
    {"nome": "Caldo em pó de carne", "forma": "po"}
]

proteinas_proibidas_sopa = [
    "Ovo"
]

legumes = [
    "Brócolis", "Cenoura", "Abobrinha", "Couve-flor",
    "Beterraba", "Vagem", "Espinafre", "Couve",
    "Repolho", "Tomate", "Pimentão", "Berinjela",
    "Abóbora", "Ervilha", "Chuchu",
    "Rúcula", "Agrião", "Alho-poró", "Salsão",

    "Cebola", "Alho", "Cebolinha", "Salsa",
    "Coentro", "Milho verde", "Palmito",

    "Pepino", "Nabo", "Rabanete",
    "Acelga", "Endívia", "Almeirão",

    "Quiabo", "Jiló", "Maxixe",
    "Batata salsa", "Inhame", "Cará"

]

unidades = [
     "kg","g","litros","ml",
     "unidade","fatia"
 ]